//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documents.DataAccess
{
    using System;
    
    public enum Roles : int
    {
        Employee = 1,
        Manager = 2
    }
}
